### ISSUE TITLE
Account Profile Page doesn't make sense

### ISSUE THREAD

**Issue by eschirtz** [samply-app/samply-desktop-releases#30]
# Account Profile Page doesn't make sense 
### Creator 
Submitted via web app 
Email: tschirtzinger@gmail.com 
### Description 
my profile icon could/should have some indication that I'm logged in (my initials? login?).. once I click on it.. I'm a bit trapped for options.. only two actionable options: 1. logout, or 2. give feedback.. no obvious way to return to the site... that's why I'm submitting this feedback now. :-)

**Comment by jmswaney** [comment]
@eschirtz Our plan worked. We'll be getting feedback from everyone now, muahahaha
