### ISSUE TITLE
In-Folder Icon

### ISSUE THREAD

**Issue by eschirtz** [samply-app/samply-desktop-releases#32]
# In-Folder Icon 
### Creator 
Submitted via web app 
Email: brginis@yahoo.com 
### Description 
The in-folder icon looks different from the application icon on the dock, just FYI

**Comment by jmswaney** [comment]
Can you see this on your Mac, @eschirtz?

**Comment by eschirtz** [comment]
I can't. I can reach out to this user and get a screenshot

**Comment by eschirtz** [comment]
Responded. Closing the ticket for now
