### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by eschirtz** [samply-app/samply-desktop-releases#34]
# Reset password 
### Creator 
Submitted via web app 
Email: jack.glur@gmail.com 
### Description 
Hi !
I downloaded Samply by creating an account.
I always generate long passwords with my password manager.
Sadly he didn't saved it, and I'm asked to log in in the app.
Apparently there's no "recover/reset" password yet ?

Thanks in advance,

Jack

**Comment by jmswaney** [comment]
Emailed back just now asking if he wants to re-signup with a new password. He already paid for a solo lifetime license.

**Comment by eschirtz** [comment]
Everyone has been so understanding so far. It’s amazing. I will try to get this set up today, along with email verification
