### ISSUE TITLE
Rename collections

### ISSUE THREAD

**Issue by eschirtz** [samply-app/samply-desktop-releases#35]
# Rename collections 
### Creator 
Submitted via web app 
Email: qkennethlu@gmail.com 
### Description 
Hey love what you guys are doing and bought a license. I am wondering if you can rename collections? It doesn't seem like it works if I hit the 3 vertical dots on the collection.

Furthermore, do you think you'll add additional categories? Like "Stab" or "Bass" etc?

Thanks!

**Comment by jmswaney** [comment]
Emailed back - mentioned that we can't rename just yet but will add in a future release. Also mentioned that we are working on adding more categories.
