### ISSUE TITLE
Group by key

### ISSUE THREAD

**Issue by eschirtz** [samply-app/samply-desktop-releases#36]
# Group by key 
### Creator 
Submitted via web app 
Email: qkennethlu@gmail.com 
### Description 
See title! Perhaps it can analyze the file name as well? Both to determine key and category

**Comment by jmswaney** [comment]
@eschirtz interesting idea here (in addition to pitch detection). We could probably benefit from regex pattern matching on file names. What do you think?

**Comment by eschirtz** [comment]
Actually yeah, we shouldn’t throw away the answers if they’re given to us!

**Comment by eschirtz** [comment]
@jmswaney have we replied to this guy?

**Comment by eschirtz** [comment]
Justin replied to another issue he submitted the same day. No need to reply now. Closing
