### ISSUE TITLE
key or tempo search?

### ISSUE THREAD

**Issue by eschirtz** [samply-app/samply-desktop-releases#37]
# key or tempo search? 
### Creator 
Submitted via web app 
Email: heyadamsmith@gmail.com 
### Description 
Hi, just wondering if there's key or tempo search?

Thanks
Adam

**Comment by jmswaney** [comment]
@eschirtz we are already planning on handling "key" in terms of pitch content, which would be more general. As for the tempo detection, we should probably make an issue in `engine` so that we can track development on this since it will likely come out afterwards.

**Comment by eschirtz** [comment]
Have we replied to Adam yet?

**Comment by eschirtz** [comment]
Just did, closing!
