### ISSUE TITLE
Samply on Windows 10

### ISSUE THREAD

**Issue by eschirtz** [samply-app/samply-desktop-releases#41]
# Samply on Windows 10 
### Creator 
Submitted via web app 
Email: lowspotfrank@gmail.com 
### Description 
Hi, I just downloaded your app to give the standard version a try on Windows 10. After loading and importing a collection, I can see the labels it generated, but the area that should contain the samples remains blank. I clicked around for a good while, but there doesn't seem to be any way to see or preview samples after import.

Thanks,
Frank

**Comment by jmswaney** [comment]
Hopefully this was related to the collection renaming bug that we recently patched
