### ISSUE TITLE
What do i do

### ISSUE THREAD

**Issue by eschirtz** [samply-app/samply-desktop-releases#49]
# What do i do 
### Creator 
Submitted via web app 
Email: richard.brown3k@gmail.com 
### Description 
I updated the app (I bought this like when yall were in beta or something). After launching, the screen is grey, with no graphics or anything. The stripe at the top is still there, but there are not any options to upload a library or anything. 

I tried just redownloading and the same thing happened.

Richard

**Comment by eschirtz** [comment]
@jmswaney We talked to this guy right?

**Comment by jmswaney** [comment]
He didn't respond to my email. I will follow up now
